baseURL = 'https://qli.jp/'
languageCode = 'ja'
title = 'Things on a planet'
theme = "ananke"

defaultContentLanguage = 'ja'

# 時間指定公開設定
buildFuture = false
buildExpired = false

# メニュー設定
[menu]
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "記事一覧"
    url = "/posts/"
    weight = 20

# その他設定
[params]
  description = "Just a personal blog"
  author = "hiro"
  date_format = "2006/01/02 03:04 pm"